run_selfcal_metric --db y1dt_dts0.5_v4.1_10yrs.db --filter g --no_clobber
run_selfcal_metric --db y1dt_dts0.5_v4.1_10yrs.db --filter r --no_clobber
run_selfcal_metric --db y1dt_dts0.5_v4.1_10yrs.db --filter i --no_clobber
run_selfcal_metric --db y1dt_dts0.5_v4.1_10yrs.db --filter z --no_clobber
run_selfcal_metric --db y1dt_dts0.5_v4.1_10yrs.db --filter y --no_clobber
run_selfcal_metric --db y1dt_dts5.0_v4.1_10yrs.db --filter g --no_clobber
run_selfcal_metric --db y1dt_dts5.0_v4.1_10yrs.db --filter r --no_clobber
run_selfcal_metric --db y1dt_dts5.0_v4.1_10yrs.db --filter i --no_clobber
run_selfcal_metric --db y1dt_dts5.0_v4.1_10yrs.db --filter z --no_clobber
run_selfcal_metric --db y1dt_dts5.0_v4.1_10yrs.db --filter y --no_clobber
